# LLM Configuration for agents
agents:
  fl_ensemble:
    provider: "ollama" # model providers: "ollama", "openai", "gemini" etc
    model: "qwen2.5-coder:latest"
    temperature: 0.3
    base_url: "http://localhost:11434/v1" # For local models, this is the URL of the local server. For cloud models, this would be the API endpoint. e.g., "https://generativelanguage.googleapis.com/v1beta/openai/"
    api_key: null  # Local models don't need a api key; For cloud models: use openai.api_key, gemini.api_key, openrouter.api_key etc (refer to config/api_keys.yaml)

  pattern_selection:
    provider: "openrouter.ai"
    model: "openai/gpt-oss-120b:nitro" #"qwen3.5:9b", # qwen2.5-coder:14b # deepseek-r1:latest gpt-oss:20b gpt-oss-120b
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.1
    # top_k: 10
    # top_p: 0.10
    api_key: 'openrouter.api_key' # follow format [provider].[api_key] based on the structure at config/api_keys.yaml

  patchgen:
    provider: "openrouter.ai"
    model: "gpt-oss-120b:nitro" #"qwen3.5:9b", # qwen2.5-coder:14b # deepseek-r1:latest gpt-oss:20b gpt-oss-120b
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.5
    # top_k: 50
    # top_p: 0.95
    api_key: null 

  debaters:
    provider: "openrouter.ai"
    model: "openai/gpt-oss-120b:nitro" #"qwen3.5:9b", # qwen2.5-coder:14b # deepseek-r1:latest gpt-oss:20b gpt-oss-120b
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.3
    # top_k: 40
    # top_p: 0.90
    api_key: 'openrouter.api_key' # follow format [provider].[api_key] based on the structure at config/api_keys.yaml

  judge:
    provider: "openrouter.ai"
    model: "openai/gpt-oss-120b:nitro" 
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.1
    # top_k: 10
    # top_p: 0.10
    api_key: 'openrouter.api_key' # follow format [provider].[api_key] based on the structure at config/api_keys.yaml


# Cost per 1,000,000 (1 Million) tokens in USD
costs:
  qwen3-coder:30b:
    input: 0.0
    output: 0.0 
  qwen2.5-coder:latest:
    input: 0.0
    output: 0.0
  qwen3.5:35b:
    input: 0.0
    output: 0.0
  gpt-4o:
    input: 0
    output: 0
  gemini-2.5-flash:
    input: 0.075
    output: 0.30
  openai/gpt-oss-120b: # standard, by openai Aug 6, 2025 131K context $0.039/M input tokens $0.19/M output tokens
    input: 0.039
    output: 0.19
  openai/gpt-oss-120b:nitro: # Released Aug 5, 2025, Knowledge cutoff Jun 30, 2024, 131,072 context, $0.039/M input tokens $0.19/M output tokens
    input: 0.039
    output: 0.19
